question_data = [
    {"text": "A slug's blood is green.", "answer": "True"},
    {"text": "The loudest animal is the African Elephant.", "answer": "False"},
    {"text": "Approximately one quarter of human bones are in the feet.", "answer": "True"},
    {"text": "The total surface area of a human lungs is the size of a football pitch.", "answer": "True"},
    {"text": "In West Virginia, USA, if you accidentally hit an animal with your car,"
             " you are free to take it home to eat.", "answer": "True"},
    {"text": "In London, UK, if you happen to die in the House of Parliament,"
             " you are entitled to a state funeral.", "answer": "False"},
    {"text": "It is illegal to pee in the Ocean in Portugal.", "answer": "True"},
    {"text": "You can lead a cow down stairs but not up stairs.", "answer": "False"},
    {"text": "Google was originally called 'Backrub'.", "answer": "True"},
    {"text": "Buzz Aldrin's mother's maiden name was 'Moon'.", "answer": "True"},
    {"text": "No piece of square dry paper can be folded in half more than 7 times.", "answer": "False"},
    {"text": "A few ounces of chocolate can to kill a small dog.", "answer": "True"}
]
question = [
    {"category": "Science     Computers", "type": "boolean", "difficulty": "medium",
     "question": "The  HTML5  standard  was  published  in  2014.", "correct_answer": "True",
     "incorrect_answers": ["False"]}, {"category": "Science     Computers", "type": "boolean", "difficulty": "medium",
                                       "question": "The  common  software-programming  acronym  %22I18N%22  comes  from  the  term  %22Interlocalization%22.",
                                       "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Science     Computers", "type": "boolean", "difficulty": "medium",
     "question": "The  very  first  recorded  computer  %22bug%22  was  a  moth  found  inside  a  Harvard  Mark  II  computer.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Science     Computers", "type": "boolean", "difficulty": "medium",
     "question": "To  bypass  US  Munitions  Export  Laws%2C  the  creator  of  the  PGP  published  all  the  source  code  in  book  form.  ",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Science     Computers", "type": "boolean", "difficulty": "medium",
     "question": "The  open  source  program  Redis  is  a  relational  database  server.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Science     Computers", "type": "boolean", "difficulty": "medium",
     "question": "Early  RAM  was  directly  seated  onto  the  motherboard  and  could  not  be  easily  removed.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Science    Computers", "type": "boolean", "difficulty": "medium",
     "question": "The  first  dual-core  CPU  was  the  Intel  Pentium  D.", "correct_answer": "False",
     "incorrect_answers": ["True"]}, {"category": "Science     Computers", "type": "boolean", "difficulty": "medium",
                                      "question": "It%27s  not  possible  to  format  a  write-protected  DVD-R  Hard  Disk.",
                                      "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Science     Computers", "type": "boolean", "difficulty": "medium",
     "question": "Android  versions  are  named  in  alphabetical  order.", "correct_answer": "True",
     "incorrect_answers": ["False"]}, {"category": "Science     Computers", "type": "boolean", "difficulty": "medium",
                                       "question": "A  Boolean  value  of  %220%22  represents  which  of  these  words%3F",
                                       "correct_answer": "False", "incorrect_answers": ["True"]}]
